# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: msftpoolagent

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs: 
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'modules'
        Contents: '**'
        TargetFolder: '$(Build.artifactstagingdirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$
        
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.ArtifactsDirectory)'
        backendServiceArm: 'az-login'
        backendAzureRmResourceGroupName: 'aessesment-rg'
        backendAzureRmStorageAccountName: 'azstgaccadopipeline'
        backendAzureRmContainerName: 'azstgblobforado'
        backendAzureRmKey: ${env:STGACCKEY}

    - task: TerraformTaskV4@4


